### PR TITLE
sn32 keyboards: migrate rgb animations to data driven

### PR DESCRIPTION
**Pull request by dexter93**
also fix build

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by dexter93** [comment]
tagging maintainers to review before merge

- @Vesek
- @iglooom
- @tbowmo
- @elpekenin
- @bausensi

Thank  you in advance guys :+1:

**Comment by elpekenin** [comment]
Relized just now that `ozone/tactical` could/should have more effects enabled, to be closer to the firmware that was shipped with it... Anyway, changes look good to me (not tested as kb is lost somewhere in a closet lol)

**Comment by Vesek** [comment]
I'll try to compile this and send the results

**Comment by Vesek** [comment]
It does work but some of the animations are probably missing, that is causing a misalignment in the menu in VIA.

**Comment by dexter93** [comment]
fixed the naming. apprently [this](https://github.com/SonixQMK/qmk_firmware/commit/675d91b813db6488ccc1ca55555ebbf0d4a45dc0#diff-2d76fe84a5e266a2dc0267d2c66a15e79361c95e378b7c58ca6731e037d3c52cR199) is how they get generated

and [these](https://github.com/the-via/reader/blob/master/src/common-menus/qmk_rgb_matrix.ts#L20-L66) are the effects VIA supports
```ts
              'All Off',
              'Solid Color',
```
are enabled by default.

Full list following for reference, rgb_matrix animations currently supported in latest `sn32_develop`

```json
    "rgb_matrix": {
        "animations": {
            "alphas_mods" : true,
            "band_pinwheel_sat" : true,
            "band_pinwheel_val" : true,
            "band_sat" : true,
            "band_spiral_sat" : true,
            "band_spiral_val" : true,
            "band_val" : true,
            "breathing" : true,
            "cycle_all" : true,
            "cycle_left_right" : true,
            "cycle_out_in" : true,
            "cycle_out_in_dual" : true,
            "cycle_pinwheel" : true,
            "cycle_spiral" : true,
            "cycle_up_down" : true,
            "digital_rain" : true,
            "dual_beacon" : true,
            "gradient_left_right" : true,
            "gradient_up_down" : true,
            "hue_breathing" : true,
            "hue_pendulum" : true,
            "hue_wave" : true,
            "jellybean_raindrops" : true,
            "multisplash" : true,
            "pixel_flow" : true,
            "pixel_fractal" : true,
            "pixel_rain" : true,
            "rainbow_beacon" : true,
            "rainbow_moving_chevron" : true,
            "rainbow_pinwheels" : true,
            "raindrops" : true,
            "solid_multisplash" : true,
            "solid_reactive" : true,
            "solid_reactive_cross" : true,
            "solid_reactive_multicross" : true,
            "solid_reactive_multinexus" : true,
            "solid_reactive_multiwide" : true,
            "solid_reactive_nexus" : true,
            "solid_reactive_simple" : true,
            "solid_reactive_wide" : true,
            "solid_splash" : true,
            "splash" : true,
            "typing_heatmap" : true,
        },
}
```

**Comment by Vesek** [comment]
Tried again, everything works as expected.

**Pull request merged**
