### PR TITLE
Add support for Tecware Phantom TKL (ANSI)

### PR DESCRIPTION
**Pull request by JonnyHaystack**
## Description

Added Tecware Phantom TKL (ANSI). Requires the 260 ChibiOS changes from https://github.com/Diff-fusion/ChibiOS-Contrib/commit/5c2bb9507a0ea2647781b882d330c56d9f22a0c7 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by dexter93** [comment]
This will probably not be merged until 260 is handled properly.
Chibios-contrib is a mess already, we do not need any extra hacks on top

**Comment by gloryhzw** [comment]
this pr can be closed since  Tecware Phantom = gmmk

**Comment by JonnyHaystack** [comment]
You're saying the switch matrix is identical? I didn't see one identical to this when I was working on it

**Comment by gloryhzw** [comment]
> You're saying the switch matrix is identical? I didn't see one identical to this when I was working on it

Yeah, the same pcb. You can use gmmk rev2 full build (or TKL pr).

**Pull request closed without merging**
