### PR TITLE
gmmk: add gmmk full rev2 support and move keyboard folder

### PR DESCRIPTION
**Pull request by gloryhzw**
## Description

1. Support gmmk rev2 VS12L03A
SPI: gmmk/full/rev3
I2C: gmmk/full/rev2 
2. Move glorious/gmmk_full to gmmk/full following gmmk/pro
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by CalcProgrammer1** [comment]
Can you resolve the conflict?

**Comment by gloryhzw** [comment]
> Can you resolve the conflict?

Keep the original file cause i do not modify that...don't know why there is conflict.

 0  keyboards/glorious/gmmk_full/chconf.h → keyboards/gmmk/full/chconf.h 
File renamed without changes.

**Comment by gloryhzw** [comment]
ok now...i have to delete the glorious folder again, quite strange

**Comment by gloryhzw** [comment]
strange....maybe the only thing i can do is to remove the old folder after this pr merged

**Comment by CalcProgrammer1** [comment]
Manually merged, though I didn't bring the sonix flasher change in.  Please submit that as its own PR.

**Pull request closed without merging**
