### PR TITLE
Update keychron k8 keymaps, and add via json file for k8 iso.

### PR DESCRIPTION
**Pull request by tbowmo**
## Description

Updating Keyboard definitions for keychron k8, mainly iso variant, also adding json file for via.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by stdvar** [comment]
thanks! overall looks good. please make minor updates to the following:
1) add readme.md into via directory to let lint pass (see failing lint in pr checks above)
2) make default_ansi -> ansi and default_iso -> iso  (default_ prefix is redundant)
3) remove VIA_ENABLE = no from iso/rules.mk else via wont work
4) add keychron/k8/via in bin/build_all.py
thanks.

**Comment by tbowmo** [comment]
@stdvar 
PR amended, let's see if the readme is accepted. via isn't a separate keymap, per se. It re-uses the ansi and iso keymap definitions.

**Comment by stdvar** [comment]
looks good. thank you.

**Comment by davecarrijo** [comment]
are via working for you guys?

**Comment by davecarrijo** [comment]
> @stdvar PR amended, let's see if the readme is accepted. via isn't a separate keymap, per se. It re-uses the ansi and iso keymap definitions.

How did you make vio work into the ISO? not working into the ANSI

**Pull request merged**
