### PR TITLE
New thing for AJAZZ AK33 & Redragon K552 (Rev 1)

### PR DESCRIPTION
**Pull request by HorrorTroll**
Reopen this pr, with better visual looking. Closed #27

## New thing
- Added new keyboard layout for Redragon K552 (Rev 1):
- [x] ISO
- [x] ABNT2

- Increase matrix scan frequency for Redragon K552 (Rev 1) & AJAZZ AK33 (Rev 1)
- Fix matrix bug for Redragon K552 (Rev 1) & AJAZZ AK33 (Rev 1)

This pr will be a good template for new openrgb branch, if ur keeb support other layout than ANSI

### CODE REVIEW

**Comment by BachoSeven** [comment]
Hi, a friend of mine has got an AJAZZ AK33 `SN32F268`(which I would be Rev 3 maybe?), which is the only variant of AK33 not supported here. Is there any particular reason for that, or do you think it would be possible to support it as well for QMK?

Thanks in advance,

F.

**Comment by CalcProgrammer1** [comment]
Is this the white LED version or the RGB version?  The non-RGB version of a
lot of these keyboards use the 268 chip.  Our support for the 268 is very
limited at the moment, though there are some people who have working ports
on it.  The other issue with 268 is that it can be bricked with no easy
recovery method unlike the 248/248B which have a permanent bootloader for
unbricking.

**Comment by BachoSeven** [comment]
White version, I should've specified that(also wrote in Discord, sorry for the duplicate).

Thanks for the explanation, it makes sense if it's so unstable.

Could you point me to the ports which have support for the 268 so I can have a look anyways?

**Comment by CalcProgrammer1** [comment]
The Womier K66 QMK port is using 268.  I think this may be the correct one,
but I'm not 100%

https://github.com/smp4488/qmk_firmware/tree/womier-k66-rgb-support

**Comment by CalcProgrammer1** [comment]
I actually have the white LED version of the K33, but I got it by mistake
as I ordered the RGB variant.  The seller never asked for it back and I got
the RGB variant elsewhere.  I suppose I could try porting to it but I
haven't had much time to look into it.

**Pull request merged**
