### PR TITLE
[Keychron K8] initial keychron k8 cleanup

### PR DESCRIPTION
**Pull request by Xelus22**
## Description

keychron k8 cleanup to align closer to core QMK layout

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* keychron k8 cleanup to align closer to core QMK layout

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by tbowmo** [comment]
Is it possible to consolidate things a bit, so we do not have to specify an iso keyboard, AND an iso layout?

Right now we have to do the following to compile:
qmk compile -kb keychron/k8/rgb/iso -km iso

So specifying iso layout twice in the command.

Also I _think_ that we can re-use the row/column definitions between ansi and iso layouts (at least on rgb mech), if I flash the keychron ansi fw into my iso keyboard all keys are functioning, except KC_NUHS (the extra ISO key besides the enter key). So the matrix is very similar between the two keyboards, and could be seen as one (default ?) with all keys in.

**Comment by Xelus22** [comment]
Unfortunately no. This is to refactor closer to QMK which the ISO and ANSI have a different number of keys. Due to the usage of the `LAYOUT` macro and not an array definition, we must differentiate between them. In addition to this, the RGB LED layout is slightly different as well due to the extra 2 keys.

**Comment by tbowmo** [comment]
What happens if you define the extra key in the ansi matrix, but just note it as kc_no/xx in LAYOUT_ansi() macro?

Anyways, it was an idea to simplify things :)

**Comment by Xelus22** [comment]
Unfortunately not because you can't "cross use" `LAYOUT` macros because they must be the correct amount of keys in the keymap.

**Pull request merged**
