### PR TITLE
[Keyboard] Ajazz AK33 RGB & Redragon K552-Old (Sonix SN32F248)

### PR DESCRIPTION
**Pull request by HorrorTroll**
## Support:
- Fully keymap (based same on stock firmware)
- Support FN+Win to lock Windows key
- LED Indicator (Caps Lock, Scroll Lock & FN+Win)
- Extra keys for audio control & system control
- Linux working (don't know about Mac OS, since I didn't use that)
- FN+Esc for bootloader
## Not support:
- PWM control for LED (so right now LED are still there, but really dimmed and hard to see)
- VIA Layer (will be update in future, when PWM control fully function)
## Additional:
- Update new way to compile by using sub-folder features
- Update new ASCII for keymap

### CODE REVIEW

**Comment by HorrorTroll** [comment]
Draft, until clean up everything for Old K552 keeb

**Comment by HorrorTroll** [comment]
Done, ready for review now.

**Comment by CalcProgrammer1** [comment]
Can you rebase your changes?  There are conflicts preventing merge.

**Comment by HorrorTroll** [comment]
Close, re-open new pr #14

**Pull request closed without merging**
