### PR TITLE
[sn32] eeprom emulation

### PR DESCRIPTION
**Pull request by dexter93**
## Description
Implement eeprom emulation for sn32 keyboards. This will allow us to store persistent values and retain them after poweroff.

Based off the original stm32 implementation.
## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by Jonty** [comment]
Does this need testing/additional work? I'd love to see this functioning & merged and am willing to help.

**Comment by dexter93** [comment]
Rebased and updated title and description. It should be functional for both 240b and 260 now.

Tested on the keychron k4 with the rgb configs. It appears to work.

**Comment by Earnestly** [comment]
Works on gmmk full rev2 (VS12L03A) iso

**Comment by l33tlinuxh4x0r** [comment]
Preliminary tests show that this is working on the k556... More to come.

**Comment by l33tlinuxh4x0r** [comment]
This also fixes bug #80 All animations and extra effects appear to work too. The only thing that I didn't test is VIA.

**Comment by IsaacDynamo** [comment]
How does this work? 
Previous code buffered a page to modify one byte, but that is now removed. Doesn't this violate assumptions made by users of EEPROM_WriteDataByte().

I expect the following to fail, because flash typically needs a page erase before it can be written again.
EEPROM_WriteDataByte(0, 0xAA);
EEPROM_WriteDataByte(0, 0x55);

~~Also I don't understand the init of value with the addr~~
`uint32_t value = *((uint32_t*)(addr & 0xFFFFFFFC));` 
 **edit** Don't know what I was thinking but this makes sense now.

I know people are already using this, and it seems to work, but I don't understand how

**Comment by dexter93** [comment]
> How does this work? Previous code buffered a page to modify one byte, but that is now removed. Doesn't this violate assumptions made by users of EEPROM_WriteDataByte().
> 
> I expect the following to fail, because flash typically needs a page erase before it can be written again. EEPROM_WriteDataByte(0, 0xAA); EEPROM_WriteDataByte(0, 0x55);
> 
> ~Also I don't understand the init of value with the addr~ `uint32_t value = *((uint32_t*)(addr & 0xFFFFFFFC));` **edit** Don't know what I was thinking but this makes sense now.
> 
> I know people are already using this, and it seems to work, but I don't understand how

The flash controller on 240b and 260 is special. It does not require an erase before writing.

**Comment by IsaacDynamo** [comment]
I see.

Looking at the datasheet for the 240 it mentions that it expects to be erased first. 
`FMC preliminarily reads the value at the addressed main Flash memory location and checks that it has been erased. If not, the program operation is skipped and a warning is issued by the PGERR bit in FLASH_STATUS register`

While 240b and 260 indeed don't mention any of this. Looking at the SYSTEM BLOCK DIAGRAM for these chips also show an EEPROM block. So it looks like these chips have an EEPROM with a flash like peripheral interface and call it flash in the datasheet.
This is really strange and unexpected behavior.

Maybe we should document this in the driver, that these chip have "flash" that doesn't need to be erased.

**Comment by IsaacDynamo** [comment]
One other question, are there any checks that prevent overlapping of program code and the eeprom pages? Something that prevents the tail of big programs to be overwritten by the eeprom emulation.

**Pull request merged**
