### PR TITLE
[SPCGear GK630K] Initial keyboard bringup

### PR DESCRIPTION
**Pull request by tfuxu**
## Description

This PR adds basic support for SPCGear GK630K. ~~VIA support isn't available for now, because I had some issues with RGB matrix after flashing, I'll investigate this later.~~ After recent updates, VIA is working properly.

I took as a base Redragon K552-2 code, with small inspirations from Keychron C1 RGB and added some improvements.

The only problem I've noticed with firmware is that the RGB matrix possibly has a different refresh rate than it should normally have, but from what I've seen this is known issue in SonixQMK branch.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/SonixQMK/qmk_firmware/issues/127

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by ppkt** [comment]
@tfuxu I just checked your branch and I noticed that there is something wrong with RGB matrix for keys: Space, Right Alt, Fn and Right Ctrl - for these keys LEDs are on for 100% of time. Also Menu button seems to be in incorrect place in matrix. I updated my branch as well so you can compare them.

**Comment by tfuxu** [comment]
@ppkt When do these problems occur? As for the keys LEDs always being on in the 6th row, they were misaligned in my old branch [spcgear_gk630k](https://github.com/tfuxu/qmk_firmware/tree/spcgear_gk630k), and has been fixed in the current branch that I'm using for this PR. Menu button was a victim of these misaligned keys and was then accidentally aligned to spacebar position.

The possibilities are that either you compiled my old branch, or SPCGear maybe released a different revision of the same keyboard with different matrix wiring.

**Comment by ppkt** [comment]
@tfuxu ohh, you're right - by accident I used your old branch (`spcgear_630k`). I just checked `spcgear_gk630k_master` and everything is working fine :)

**Comment by tfuxu** [comment]
@ppkt Good to know that everything's working fine, and thanks for feedback

**Comment by mmuras** [comment]
@tfuxu Thanks for your godly work! Was just searching for this. Is VIA working for you? I compiled from master and then from updated branch (obviously with via keymap) for gk630k and cannot seem to get it to work. Trying with either webapp from caniusevia or VIA installed on windows to no avail.
Could you help me out with sorting this?

**Comment by tfuxu** [comment]
I haven't used VIA since I've moved to Linux, but I can check it for you tomorrow.

**Comment by mmuras** [comment]
I would be grateful :)

**Comment by tfuxu** [comment]
@Muraske
You probably didn't manually load a JSON file in VIA. You can do this by toggling the `Show Design tab` setting in Settings tab. In Design tab you need to load a draft definition, this will be for you a `gk630k.json` file, which is located in a root directory of this keyboard. After that, you should be ready to go :)
As a sidenote, I would recommend you to use [Vial](https://github.com/vial-kb/vial-gui) instead of VIA, because it takes less computer resources, and it's easier to load a JSON file from it.

**Comment by mmuras** [comment]
Thank you! I will try this as soon as I get back home :) Thank you for the tips!

**Pull request merged**
