### PR TITLE
Add keyboard [DREVO Calibur V2 TE]

### PR DESCRIPTION
**Pull request by marksard**
## Description

I have reverse engineered a Drevo Calibur V2 TE.
https://github.com/marksard/re-drevo-calibur-v2-te

Also, the ROYAL KLUDGE RK71 and Monstergear Ninja71 probably use the same PCB, but this is unconfirmed.  

product info
https://www.drevo.net/jp/node/131

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

### CODE REVIEW

**Comment by Jpe230** [comment]
I have a similar board with the same pinout (albeit it has an ISO layout).  Does your keyboard have this issue #124 regarding the RGB matrix?

**Comment by marksard** [comment]
> I have a similar board with the same pinout (albeit it has an ISO layout). Does your keyboard have this issue #124 regarding the RGB matrix?

At least the LEDs on the PCB of the product I own are working fine with my code.

**Comment by marksard** [comment]
This PR can be closed by an updated new PR.
https://github.com/SonixQMK/qmk_firmware/pull/262

**Comment by guilleortas** [comment]
> I have a similar board with the same pinout (albeit it has an ISO layout). Does your keyboard have this issue #124 regarding the RGB matrix?

I have the same issue with my ISO Drevo V2 TE. Have you been able to fix it?

**Pull request closed without merging**
