### PR TITLE
Add support for Friendly Foes Foundry FFC61

### PR DESCRIPTION
**Pull request by ejiije**
## Description

Added support for the Friendly Foes Foundry FFC61. 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by CalcProgrammer1** [comment]
Why is there a rev2 folder?  I'm cleaning this up to match the latest changes and have the ffc61 folder cleaned and building, but what is rev2?  It has some temporary old files in it.  Can I just delete rev2 or are there 2 revisions of the FFC61?

If there are 2 revisions, I'd recommend doing ffc/ffc61/rev1 and ffc/ffc61/rev2 (similar to AK33 and Redragon K552).

**Comment by ejiije** [comment]
Oh yeah I'm sorry! I based it off the AK33 build and I used the rev2 folder to test a few things. I must've forgotten to remove it before uploading. Please feel free to delete it. Thanks!

**Comment by ejiije** [comment]
> Why is there a rev2 folder?  I'm cleaning this up to match the latest changes and have the ffc61 folder cleaned and building, but what is rev2?  It has some temporary old files in it.  Can I just delete rev2 or are there 2 revisions of the FFC61?
> 
> 
> 
> If there are 2 revisions, I'd recommend doing ffc/ffc61/rev1 and ffc/ffc61/rev2 (similar to AK33 and Redragon K552).


Oh yeah I'm sorry! I based it off the AK33 build and I used the rev2 folder to test a few things. I must've forgotten to remove it before uploading. Please feel free to delete it. Thanks!

**Comment by CalcProgrammer1** [comment]
Awesome, manually merged then.

**Comment by CalcProgrammer1** [comment]
Please test when the build is ready, I moved to using shared led_matrix and matrix files and I'm pretty sure it will work fine but I'd like you to verify.  I will rebase sn32_openrgb and enable it in there next.

**Comment by ejiije** [comment]
> Please test when the build is ready, I moved to using shared led_matrix and matrix files and I'm pretty sure it will work fine but I'd like you to verify.  I will rebase sn32_openrgb and enable it in there next.

Got it, will try as soon as I can.

**Pull request closed without merging**
