### PR TITLE
[GMMK compact] Make it possible to disable RGB

### PR DESCRIPTION
**Pull request by NilsIrl**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by dexter93** [comment]
disabling RGB should be possible without this using `RGB_TOG` key. Why nuke the driver?

**Comment by NilsIrl** [comment]
I didn't know that was possible. I just changed something in rules.mk (`SOMEKEY = NO`).

I can't remember what `SOMEKEY` was exactly.

But this patch was required to fix the error that appeared as a result of that.

**Comment by dexter93** [comment]
`SOMEKEY` was `RGB_MATRIX_ENABLE`. Please read further [here](https://docs.qmk.fm/#/feature_rgb_matrix)

**Comment by NilsIrl** [comment]
Yes, that's not the issue. The issue is that setting that key (which I had forgotten at the time of writing my last comment), means that it doesn't compile anymore (unless this patch is applied).

**Pull request closed without merging**
