### PR TITLE
[Keychron C1 White] Bringup

### PR DESCRIPTION
**Pull request by IsaacDynamo**
## Description

This PR adds support for Keychron C1 White keyboard.
Currently there is no VIA support, because I could not fit the build into the RAM. 

Improvements / Follow up PRs
- Move SN32F260_defines.h into chibios-contrib. This header file is generated from the vendor provided .svd file. 
- Move the shared matrix driver for 260 to a generic location, so it can be used by other boards.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by vjdato21 — CHANGES_REQUESTED** [review]
Shouldn't it be?
`'keychron/c1/white'`

**Comment by IsaacDynamo** [comment]
> Shouldn't it be? `'keychron/c1/white'`

What should be?

**Comment by vjdato21** [comment]
> > Shouldn't it be? `'keychron/c1/white'`
> 
> What should be?

bin/build_all.py

**Comment by vjdato21** [comment]
It should be `keychron/c1/white` rather than `keychron/white/c1`. So edit the file in `bin/build_all.py`

**Comment by dexter93** [comment]
is there a reason for using the RGB Matrix and not [LED Matrix](https://docs.qmk.fm/#/feature_led_matrix?id=led-matrix-lighting)?

**Pull request merged**
