### PR TITLE
sn32: usb hal cleanup

### PR DESCRIPTION
**Pull request by dexter93**
status: _**done**_
- Usb hal gone native
- USB start/stop/restart working now
- Enumeration delay gone
- wakeup working
- suspend working
- mac working
- console working
The bulk code for this lives in https://github.com/SonixQMK/ChibiOS-Contrib/pull/42

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by fightforlife** [comment]
Would love to see this merged. Working good on my K66 build. Could verify the start/wake/suspend. Initial delay is gone. Although I could not check the console and mac.

**Comment by stdvar** [comment]
i cannot comment on chibios side in github since it is not a pr. so adding it here in conversation section:
1) i would prefer avoid tempering with usb chibios state machine here. since it shouldbe handled by callback. 
```
        if (iwIntFlag & mskEP0_SETUP) {
            /* SETUP */
            /* Clear receiving in the chibios state machine */
            (usbp)->receiving &= ~1;
```
any particular reason why it is needed?

2) same goes for address assignment.
why it is needed here?
```
            /* Special case for SetAddress for EP0*/
            if((((uint16_t)usbp->setup[0]<<8)|usbp->setup[1]) == 0x0500) {
              usbp->address = usbp->setup[2];
              usb_lld_set_address(usbp);
              _usb_isr_invoke_event_cb(usbp, USB_EVENT_ADDRESS);
              usbp->state = USB_SELECTED;
              usb_lld_stall_in(usbp, 0);
            }
```

3) why do we care about lock from isr? we are already in interrupt...
```
                osalSysLockFromISR();
                sn32_usb_write_fifo(0, isp->txbuf, txed, true);
                osalSysUnlockFromISR();
```

4) please make sure that several interrupts are handled here. since handleAck outside of for loop only last ack is handled.
```
        for(int i=1; i <= USB_MAX_ENDPOINTS; i++) {
            if (iwIntFlag & mskEPn_ACK(i)){
                ep = i;
            }
        }
        handleACK(usbp, ep);
        SN32_USB->INSTSC = (mskEPn_ACK(ep));
```

5) same goes for handleNAK
6) when usb_lld_read_setup we are not in interrupt, are we?
```
void usb_lld_read_setup(USBDriver *usbp, usbep_t ep, uint8_t *buf) {
    osalSysLockFromISR();
    sn32_usb_read_fifo(ep, buf, 8, false);
    osalSysUnlockFromISR();
}
```
7) when usb_lld_start_in is called we  are not in interrupt. why osalSysLockFromISR is used?
```
void usb_lld_start_in(USBDriver *usbp, usbep_t ep)
{
    size_t n;
    USBInEndpointState *isp = usbp->epc[ep]->in_state;

    /* Transfer initialization.*/
    n = isp->txsize;

    if((n >= 0) || (ep == 0)) {

        if (n > (size_t)usbp->epc[ep]->in_maxsize)
            n = (size_t)usbp->epc[ep]->in_maxsize;

        isp->txlast = n;
        osalSysLockFromISR();
        sn32_usb_write_fifo(ep, isp->txbuf, n, false);
        osalSysUnlockFromISR();
```


rest looks good. thanks.

**Comment by dexter93** [comment]
> i cannot comment on chibios side in github since it is not a pr. so adding it here in conversation section:
> 
> 1. i would prefer avoid tempering with usb chibios state machine here. since it shouldbe handled by callback.
> 
> ```
>         if (iwIntFlag & mskEP0_SETUP) {
>             /* SETUP */
>             /* Clear receiving in the chibios state machine */
>             (usbp)->receiving &= ~1;
> ```
> 
> any particular reason why it is needed?
> 
> 2. same goes for address assignment.
>    why it is needed here?
> 
> ```
>             /* Special case for SetAddress for EP0*/
>             if((((uint16_t)usbp->setup[0]<<8)|usbp->setup[1]) == 0x0500) {
>               usbp->address = usbp->setup[2];
>               usb_lld_set_address(usbp);
>               _usb_isr_invoke_event_cb(usbp, USB_EVENT_ADDRESS);
>               usbp->state = USB_SELECTED;
>               usb_lld_stall_in(usbp, 0);
>             }
> ```
> 
> 3. why do we care about lock from isr? we are already in interrupt...
> 
> ```
>                 osalSysLockFromISR();
>                 sn32_usb_write_fifo(0, isp->txbuf, txed, true);
>                 osalSysUnlockFromISR();
> ```
> 
> 4. please make sure that several interrupts are handled here. since handleAck outside of for loop only last ack is handled.
> 
> ```
>         for(int i=1; i <= USB_MAX_ENDPOINTS; i++) {
>             if (iwIntFlag & mskEPn_ACK(i)){
>                 ep = i;
>             }
>         }
>         handleACK(usbp, ep);
>         SN32_USB->INSTSC = (mskEPn_ACK(ep));
> ```
> 
> 5. same goes for handleNAK
> 6. when usb_lld_read_setup we are not in interrupt, are we?
> 
> ```
> void usb_lld_read_setup(USBDriver *usbp, usbep_t ep, uint8_t *buf) {
>     osalSysLockFromISR();
>     sn32_usb_read_fifo(ep, buf, 8, false);
>     osalSysUnlockFromISR();
> }
> ```
> 
> 7. when usb_lld_start_in is called we  are not in interrupt. why osalSysLockFromISR is used?
> 
> ```
> void usb_lld_start_in(USBDriver *usbp, usbep_t ep)
> {
>     size_t n;
>     USBInEndpointState *isp = usbp->epc[ep]->in_state;
> 
>     /* Transfer initialization.*/
>     n = isp->txsize;
> 
>     if((n >= 0) || (ep == 0)) {
> 
>         if (n > (size_t)usbp->epc[ep]->in_maxsize)
>             n = (size_t)usbp->epc[ep]->in_maxsize;
> 
>         isp->txlast = n;
>         osalSysLockFromISR();
>         sn32_usb_write_fifo(ep, isp->txbuf, n, false);
>         osalSysUnlockFromISR();
> ```
> 
> rest looks good. thanks.

Hi, thanks for taking a look. Will try to summarize things here
1. This is borrowed from the KINETIS implementation, see https://github.com/SonixQMK/ChibiOS-Contrib/blob/sn32_master/os/hal/ports/KINETIS/LLD/USBHSv1/hal_usb_lld.c#L245-L258
2. Same as above https://github.com/SonixQMK/ChibiOS-Contrib/blob/sn32_master/os/hal/ports/KINETIS/LLD/USBHSv1/hal_usb_lld.c#L262-L269

The reason for those is that KINETIS is using the same logic for SETUP and Address assignment. We have the limitation of those having to be handled inside the interrupt, so doing it this way allows us to wrap the setup/enumeration procedure around Chibios in an elegant way. We can now simply use `USB_LATE_SET_ADDRESS` and update the machine state accordingly instead of faking the state to completion and picking up the Address in the next interrupt. We are overriding the core `usb_set_address` functionality in a way that allows it to be properly declared and in time. We get rid of temporary storage of the USB Address and it results in a more reliable SETUP operation.

3,6. We are already in an interrupt on 3, but doing a kernel lock there makes sure that hardware i/o gets done reliably when there is stuff to be written/read, avoids weird stuff happening there. As for 6, although not in an interrupt state, follows the same logic. A kernel lock is requested while the i/o is going on. This might be overkill/moot, but I have not observed any drawbacks yet. Same for 7.

4,5. The loop is just scanning for the ep to be handled by handleNAK/ACK in the interrupt triggered. Since we don't pass the ep arg when calling the interrupt handler, the LLD must know what ep to process. A more elegant solution might be doing that first and getting rid of the loop. This assumes however that no two ep[1-MAX] interrupts are fired at the same time, thus we might end up with some dropped ones. I am not sure of the possibility of that happening, the possible fix for that is stated above.

**Comment by stdvar** [comment]
good job! thank you for looking into it.

**Pull request merged**
