### PR TITLE
Add initial support for Redragon K580 (resolves #33)

### LINKED ISSUE #33: [Redragon K580 VATA] Add support
Reports as VID = 0C45, PID = 5004. I believe these to be the same as the Redragon K556 (source: https://youtu.be/2MHtLEiXaXg?t=1195). This is my first time taking a keyboard apart, but managed to take some pictures of the inside, and what I believe to be the chip running everything (apologies for the quality). As I'm new to this kind of stuff, I doubt I can solder anything onto the board (I don't even have a soldering iron), would love to hear if there's any way around this.

IMG_20210426_142932
IMG_20210426_142942
IMG_20210426_143002

### PR DESCRIPTION
**Pull request by tkon99**
## Description

Added support for the Redragon K580 VATA. Features todo:
- [ ] Win Lock LED indicator
- [X] Macro keys LEDs
- [ ] Volume/Brightness switch button LED
- [X] Side LEDs
- [ ] Creation of a proper Configurator config
- [ ] Split keymaps into default & manufacturer-matching to comply with QMKs guidelines

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #33 

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by senposage** [comment]
are all the open items resolved ?

**Comment by tkon99** [comment]
@senposage I believe that's the case, only thing missing is correct configurator layout, might add it in the future

**Review by senposage — APPROVED** [review]

**Comment by tkon99** [comment]
Can we merge this PR entirely? It has no conflicts and is finished.

**Comment by senposage** [comment]
No Real Problems here the stock fn+win to toggle winlock doesn't work but that doesn't matter ?

**Comment by tkon99** [comment]
That's the only issue, can be added but would increase keymap size too much for it's benefit I think.

**Pull request merged**
